# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z2OhAk3n566ODU1-BRKxrC50CVs7Kits
"""

##tarea del 14_11_2024
# programacion

import streamlit as st
# Título de la aplicación
st.title('Mi Primera Aplicación Web con Streamlit')
# Texto simple
st.write('Esta es una aplicación web de ejemplo utilizando Streamlit.')

